version: 2
jobs:
  build:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - restore_cache:
        key: project-cache
    - run:
        name: Check
        command: cargo check
    - save_cache:
        key: project-cache
        paths:
          - "~/.cargo"
          - "./target"
