version: 2
jobs:
  build:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - restore_cache:
        key: project-cache
    - run:
        name: Check
        command: cargo check
    - save_cache:
        key: project-cache
        paths:
          - "~/.cargo"
          - "./target"
  publish:
    docker:
    - image: debian:buster
    steps:
    - run:
        name: Publish
        command: echo Publish
workflows:
    version: 2
    build:
      jobs:
      - build:
          filters:
            branches:
              only:
              - master
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
