version: 2
jobs:
  check:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - restore_cache:
        key: check-cache
    - run:
        name: Check
        command: cargo check
    - save_cache:
        key: check-cache
        paths:
          - "~/.cargo"
          - "./target"
  build:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - run:
        name: Build
        command: RUSTFLAGS="-C link-arg=-s" cargo build --release
  publish:
    docker:
    - image: cibuilds/github:0.13
    steps:
    - run:
        name: Publish
        command: ghr -u ${CIRCLE_USERNAME} ${CIRCLE_TAG}
workflows:
    version: 2
    check:
      jobs:
      - check:
          filters:
            branches:
              only: master
    build-and-publish:
      jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
