version: 2
jobs:
  check:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - restore_cache:
        key: check-cache
    - run:
        name: Check
        command: cargo check
    - save_cache:
        key: check-cache
        paths:
          - "~/.cargo"
          - "./target"
  build:
    docker:
    - image: circleci/rust:1.39-buster
    steps:
    - checkout
    - run:
        name: Build
        command: RUSTFLAGS="-C link-arg=-s" cargo build --release
    - persist_to_workspace:
        root: target/release
        paths:
        - cd-to-csv
        - cd-to-notice
        - cl-to-cd
  publish:
    docker:
    - image: cibuilds/github:0.13
    steps:
    - attach_workspace:
        at: workspace
    - run:
        name: Tarball
        command: |
          NAME=cl-to-cd_${CIRCLE_TAG}_linux_x86_64
          mkdir ${NAME}
          cp workspace/* ${NAME}
          tar -czvf ${NAME}.tar.gz ${NAME}/*
    - run:
        name: Publish
        command: |
          if [[ ${CIRCLE_TAG} = *alpha* || ${CIRCLE_TAG} = *beta* ]]; then
            PRE=-prerelease
          else
            PRE=
          fi
          ghr \
          -u ${CIRCLE_PROJECT_USERNAME} \
          -r ${CIRCLE_PROJECT_REPONAME} \
          -c ${CIRCLE_SHA1} \
          ${PRE} \
          ${CIRCLE_TAG} *.tar.gz
workflows:
    version: 2
    check:
      jobs:
      - check:
          filters:
            branches:
              only: master
    build-and-publish:
      jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
              - /v[0-9]+\.[0-9]+\.[0-9]+.*/
